### PR TITLE
Change flash color at runtime + description update

### PR DESCRIPTION
**Pull request by Sword352**
haha second pr of the day

- Made a variable to change the flash color at runtime
- Description update about the screenshot path

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]

**Comment by moxie-coder** [comment]
gonna be using these updates for the android compatible port

**Comment by Sword352** [comment]
Alr
Prob gonna do a third pr with more customizations and code formatting cuz this plugins awesome

**Comment by moxie-coder** [comment]
> Alr
> Prob gonna do a third pr with more customizations and code formatting cuz this plugins awesome

agreed 👍

**Comment by Sword352** [comment]
closing this cuz makin a new bigger commit lol

**Comment by moxie-coder** [comment]
> closing this cuz makin a new bigger commit lol

alr lol

**Pull request closed without merging**
