### PR TITLE
Big update

### PR DESCRIPTION
**Pull request by Sword352**
So many things (slay)
Cant explain everything just look at the code its huge lol

Still known issues:
- `BitmapData`s wont resize when we resize the window and that the screenshot display is visible
- Screenshots won't take everything, like alpha from shaders and such

### CODE REVIEW

**Review by moxie-coder — APPROVED** [review]
damn lol, it’s good tho, I like the new changes 👍

**Comment by Sword352** [comment]
ikr this should be 2.0

**Comment by dotevie** [comment]
slay

**Comment by moxie-coder** [comment]
> ikr this should be 2.0

agreed

**Comment by moxie-coder** [comment]
> slay

😎

**Pull request merged**
